sudo: required
services:
  - docker

before_install:
  - docker build -t antonzotov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonzotov/react-test npm test

after_success:
  - docker build -t antonzotov/multi-client ./client
  - docker build -t antonzotov/multi-nginx ./nginx
  - docker build -t antonzotov/multi-server ./server
  - docker build -t antonzotov/multi-worker ./worker
  # Log in to the docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push antonzotov/multi-client
  - docker push antonzotov/multi-nginx
  - docker push antonzotov/multi-server
  - docker push antonzotov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-489172308893"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
